/** Framework-neutral state and drag-drop adapter for the PROVA Studio test-step canvas. */

/** Test actions supported by the Studio canvas. */
export type TestStepAction =
  | 'navigate'
  | 'click'
  | 'fill'
  | 'select'
  | 'assert'
  | 'api-request'
  | 'wait';

/** One editable test step on the Studio canvas. */
export interface StudioTestStep {
  id: string;
  action: TestStepAction;
  label: string;
  target?: string;
  value?: string;
  timeoutMs?: number;
  disabled?: boolean;
}

/** Input used when adding a step; identifiers are generated by the canvas. */
export type NewStudioTestStep = Omit<StudioTestStep, 'id'>;

/** Drop location compatible with react-beautiful-dnd and @hello-pangea/dnd. */
export interface CanvasDropLocation {
  droppableId: string;
  index: number;
}

/** Drop result compatible with react-beautiful-dnd and @hello-pangea/dnd. */
export interface CanvasDropResult {
  draggableId: string;
  source: CanvasDropLocation;
  destination?: CanvasDropLocation | null;
}

/** Snapshot emitted after each successful canvas change. */
export interface TestStepCanvasSnapshot {
  revision: number;
  steps: readonly StudioTestStep[];
  selectedStepId?: string;
}

/** Canvas configuration. */
export interface TestStepCanvasOptions {
  initialSteps?: readonly StudioTestStep[];
  idFactory?: () => string;
  droppableId?: string;
  maximumSteps?: number;
}

/** Result of applying a drag-drop event. */
export interface CanvasDropOutcome {
  changed: boolean;
  reason?: 'outside-canvas' | 'different-canvas' | 'unchanged';
  snapshot: TestStepCanvasSnapshot;
}

type CanvasListener = (snapshot: TestStepCanvasSnapshot) => void;

const ACTIONS = new Set<TestStepAction>([
  'navigate', 'click', 'fill', 'select', 'assert', 'api-request', 'wait'
]);

function cloneStep(step: StudioTestStep): StudioTestStep {
  return { ...step };
}

function defaultIdFactory(): string {
  return `step-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

function validateStep(step: StudioTestStep): void {
  if (!step.id.trim()) throw new Error('Step id must be a non-empty string');
  if (!ACTIONS.has(step.action)) throw new Error(`Unsupported test step action: ${String(step.action)}`);
  if (!step.label.trim()) throw new Error('Step label must be a non-empty string');
  if (step.timeoutMs !== undefined &&
      (!Number.isInteger(step.timeoutMs) || step.timeoutMs < 1)) {
    throw new Error('Step timeoutMs must be a positive integer');
  }
}

/**
 * Manages add, reorder, select, update, and remove operations for a Studio canvas.
 *
 * The `applyDrop` input intentionally matches the common React DnD drop-result
 * shape, allowing UI packages to call it directly from `onDragEnd`.
 */
export class TestStepCanvas {
  private steps: StudioTestStep[];
  private selectedStepId: string | undefined;
  private revision = 0;
  private readonly listeners = new Set<CanvasListener>();
  private readonly idFactory: () => string;
  private readonly droppableId: string;
  private readonly maximumSteps: number;

  /** Creates a test-step canvas. */
  constructor(options: TestStepCanvasOptions = {}) {
    this.idFactory = options.idFactory ?? defaultIdFactory;
    this.droppableId = options.droppableId ?? 'prova-test-step-canvas';
    this.maximumSteps = options.maximumSteps ?? 500;
    if (!Number.isInteger(this.maximumSteps) || this.maximumSteps < 1) {
      throw new Error('maximumSteps must be a positive integer');
    }
    this.steps = (options.initialSteps ?? []).map(cloneStep);
    this.assertValidCollection(this.steps);
    if (this.steps.length > this.maximumSteps) {
      throw new Error(`Canvas cannot contain more than ${this.maximumSteps} steps`);
    }
  }

  /** Returns an immutable copy of current canvas state. */
  getSnapshot(): TestStepCanvasSnapshot {
    return {
      revision: this.revision,
      steps: this.steps.map((step) => Object.freeze(cloneStep(step))),
      ...(this.selectedStepId ? { selectedStepId: this.selectedStepId } : {})
    };
  }

  /** Adds a step at an optional position and returns its generated identifier. */
  addStep(step: NewStudioTestStep, index = this.steps.length): string {
    if (this.steps.length >= this.maximumSteps) {
      throw new Error(`Canvas cannot contain more than ${this.maximumSteps} steps`);
    }
    this.assertInsertionIndex(index);
    const id = this.idFactory();
    const created: StudioTestStep = { id, ...step };
    validateStep(created);
    if (this.steps.some((existing) => existing.id === id)) {
      throw new Error(`Step id already exists: ${id}`);
    }
    this.steps.splice(index, 0, cloneStep(created));
    this.changed();
    return id;
  }

  /** Replaces editable fields on an existing step. */
  updateStep(id: string, changes: Partial<NewStudioTestStep>): void {
    const index = this.indexOf(id);
    const updated = { ...this.steps[index], ...changes };
    validateStep(updated);
    this.steps[index] = updated;
    this.changed();
  }

  /** Removes and returns a step. */
  removeStep(id: string): StudioTestStep {
    const index = this.indexOf(id);
    const [removed] = this.steps.splice(index, 1);
    if (this.selectedStepId === id) this.selectedStepId = undefined;
    this.changed();
    return cloneStep(removed);
  }

  /** Moves a step between zero-based canvas positions. */
  reorderStep(fromIndex: number, toIndex: number): void {
    this.assertExistingIndex(fromIndex);
    this.assertExistingIndex(toIndex);
    if (fromIndex === toIndex) return;
    const [step] = this.steps.splice(fromIndex, 1);
    this.steps.splice(toIndex, 0, step);
    this.changed();
  }

  /** Applies a React DnD-compatible `onDragEnd` result. */
  applyDrop(result: CanvasDropResult): CanvasDropOutcome {
    if (!result.destination) {
      return { changed: false, reason: 'outside-canvas', snapshot: this.getSnapshot() };
    }
    if (result.source.droppableId !== this.droppableId ||
        result.destination.droppableId !== this.droppableId) {
      return { changed: false, reason: 'different-canvas', snapshot: this.getSnapshot() };
    }
    this.assertExistingIndex(result.source.index);
    this.assertExistingIndex(result.destination.index);
    if (this.steps[result.source.index].id !== result.draggableId) {
      throw new Error(`Dragged step ${result.draggableId} does not match source index ${result.source.index}`);
    }
    if (result.source.index === result.destination.index) {
      return { changed: false, reason: 'unchanged', snapshot: this.getSnapshot() };
    }
    this.reorderStep(result.source.index, result.destination.index);
    return { changed: true, snapshot: this.getSnapshot() };
  }

  /** Selects a step for editing, or clears the selection with no identifier. */
  selectStep(id?: string): void {
    if (id !== undefined) this.indexOf(id);
    if (this.selectedStepId === id) return;
    this.selectedStepId = id;
    this.changed();
  }

  /** Moves the selected step one position for keyboard-accessible reordering. */
  moveSelected(direction: 'up' | 'down'): boolean {
    if (!this.selectedStepId) return false;
    const current = this.indexOf(this.selectedStepId);
    const destination = direction === 'up' ? current - 1 : current + 1;
    if (destination < 0 || destination >= this.steps.length) return false;
    this.reorderStep(current, destination);
    return true;
  }

  /** Registers a change listener and returns an unsubscribe callback. */
  subscribe(listener: CanvasListener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  /** Serializes the ordered step list for persistence or execution. */
  toJSON(): string {
    return JSON.stringify(this.steps);
  }

  /** Restores a canvas from serialized ordered steps. */
  static fromJSON(json: string, options: Omit<TestStepCanvasOptions, 'initialSteps'> = {}): TestStepCanvas {
    let parsed: unknown;
    try {
      parsed = JSON.parse(json);
    } catch (error) {
      throw new Error(`Invalid canvas JSON: ${error instanceof Error ? error.message : String(error)}`);
    }
    if (!Array.isArray(parsed)) throw new Error('Canvas JSON must contain an array of steps');
    return new TestStepCanvas({ ...options, initialSteps: parsed as StudioTestStep[] });
  }

  private changed(): void {
    this.revision += 1;
    const snapshot = this.getSnapshot();
    for (const listener of this.listeners) listener(snapshot);
  }

  private indexOf(id: string): number {
    const index = this.steps.findIndex((step) => step.id === id);
    if (index < 0) throw new Error(`Test step not found: ${id}`);
    return index;
  }

  private assertValidCollection(steps: readonly StudioTestStep[]): void {
    const ids = new Set<string>();
    for (const step of steps) {
      validateStep(step);
      if (ids.has(step.id)) throw new Error(`Duplicate test step id: ${step.id}`);
      ids.add(step.id);
    }
  }

  private assertExistingIndex(index: number): void {
    if (!Number.isInteger(index) || index < 0 || index >= this.steps.length) {
      throw new Error(`Step index out of range: ${index}`);
    }
  }

  private assertInsertionIndex(index: number): void {
    if (!Number.isInteger(index) || index < 0 || index > this.steps.length) {
      throw new Error(`Insertion index out of range: ${index}`);
    }
  }
}
